name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Test
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo test
      - name: Build
        run: |
          cargo build --release

        env:
          CARGO_TARGET_DIR: ${{ runner.temp }}/target
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Semantic Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }},
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
