name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
          
      - name: Build
        run: cargo build --release

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }},
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
